[package]
name = "easymediacompressor"
version = "0.1.0"
build = "build.rs"
edition = "2021"


[dependencies]
chrono = "0.4.37"
cmd_lib = "1.9.3"
rfd = "0.14.1"
slint = "1.5.1"

[build-dependencies]
slint-build = "1.5.1"
